.\" Copyright 2024, Adelsbach UG (haftungsbeschraenkt)
.\" Copyright 2014-2024, Jan Adelsbach <jan@jadelsbach.de>
.\"
.\" Permission is hereby granted, free of charge, to any person obtaining 
.\" a copy of this software and associated documentation files
.\" (the “Software”), 
.\" to deal in the Software without restriction, including without limitation 
.\" the rights to use, copy, modify, merge, publish, distribute, sublicense, 
.\" and/or sell copies of the Software, and to permit persons to whom the 
.\" Software is furnished to do so, subject to the following conditions:
.\" 
.\" The above copyright notice and this permission notice shall be included 
.\" in all copies or substantial portions of the Software.
.\"
.\" THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS 
.\" OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
.\" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
.\" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
.\" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
.\" FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
.\" DEALINGS IN THE SOFTWARE.
.Dd $Mdocdate: May 9 2020 $
.Dt mtx_destroy 3
.Os
.Sh NAME
.Nm mtx_destroy
.Nd destroy a mutex
.Sh SYNOPSIS
.Lb threads
.In threads.h
.Ft int
.Fn mtx_destroy "mtx_t *mtx"
.Sh DESCRIPTION
The function
.Fn mtx_destroy
destroy the given mutex
.Fa mtx .
.Pp
There must be no threads waiting on the given mutex when it is destroyed.
.Sh RETURN VALUES
Upon success
.Fn mtx_destroy
returns 
.Va thrd_success , 
in the case of an error
.Va thrd_error
will be returned. 
.Sh SEE ALSO
.Xr mtx_init 3
.Xr mtx_lock 3
.Xr mtx_timedlock 3
.Xr mtx_trylock 3
.Xr mtx_unlock 3
.Sh HISTORY
The
.Fn mtx_destroy
function first appeared in the C11 standard ISO/IEC 9899:2011.
.Sh AUTHORS
Jan Adelsbach <jan@jadelsbach.de>
 
